
import {
  Facebook,
  FileText,
  Globe,
  Instagram,
  Linkedin,
  Baseline,
  Twitter,
  MessageSquare,
  Headphones,
  ShoppingBag,
  Phone,
  Bookmark,
  Slack,
  Mail,
  Plug,
} from "lucide-react";
import { Integration } from "@/types/integration";

// Lista de integraciones disponibles
export const integrationsList: Integration[] = [
  {
    id: "slack",
    name: "Slack",
    description: "Integra tus agentes con canales de Slack para automatizar respuestas y notificaciones",
    icon: <Slack className="h-8 w-8 text-purple-500" />,
    status: "disconnected",
    category: "productivity",
    popularityScore: 94,
  },
  {
    id: "office365",
    name: "Office 365",
    description: "Conecta con Microsoft Office 365 para automatizar tareas en Outlook, Teams y más",
    icon: <Mail className="h-8 w-8 text-blue-400" />,
    status: "disconnected",
    category: "productivity",
    popularityScore: 89,
  },
  {
    id: "meta-ads",
    name: "Meta Ads",
    description: "Conecta y gestiona tus campañas publicitarias en Meta (Facebook, Instagram)",
    icon: <Facebook className="h-8 w-8 text-blue-600" />,
    status: "connected",
    category: "marketing",
    connectedDate: "2024-01-15",
    popularityScore: 92,
  },
  {
    id: "google-drive",
    name: "Google Drive",
    description: "Accede a documentos y archivos almacenados en Google Drive",
    icon: <FileText className="h-8 w-8 text-green-600" />,
    status: "disconnected",
    category: "productivity",
    popularityScore: 88,
  },
  {
    id: "instagram-business",
    name: "Instagram Business",
    description: "Gestiona tus cuentas profesionales de Instagram",
    icon: <Instagram className="h-8 w-8 text-pink-600" />,
    status: "connected",
    category: "social",
    connectedDate: "2024-02-20",
    popularityScore: 95,
  },
  {
    id: "facebook-pages",
    name: "Facebook Pages",
    description: "Administra tus páginas de Facebook y su contenido",
    icon: <Facebook className="h-8 w-8 text-blue-600" />,
    status: "connected",
    category: "social",
    connectedDate: "2024-02-10",
    popularityScore: 90,
  },
  {
    id: "x",
    name: "X",
    description: "Publica y analiza contenido en X (anteriormente Twitter)",
    icon: <Twitter className="h-8 w-8 text-black" />,
    status: "disconnected",
    category: "social",
    popularityScore: 82,
  },
  {
    id: "threads",
    name: "Threads",
    description: "Conecta tu cuenta de Threads para publicar y gestionar contenido",
    icon: <MessageSquare className="h-8 w-8 text-purple-600" />,
    status: "pending",
    category: "social",
    popularityScore: 75,
  },
  {
    id: "metricool",
    name: "Metricool",
    description: "Plataforma para analítica y programación de redes sociales",
    icon: <Baseline className="h-8 w-8 text-blue-500" />,
    status: "disconnected",
    category: "marketing",
    popularityScore: 78,
  },
  {
    id: "linkedin",
    name: "LinkedIn",
    description: "Conecta con perfiles profesionales y páginas de empresa",
    icon: <Linkedin className="h-8 w-8 text-blue-700" />,
    status: "connected",
    category: "social",
    connectedDate: "2024-03-05",
    popularityScore: 87,
  },
  {
    id: "elevenlabs",
    name: "ElevenLabs",
    description: "Convierte texto a voz de alta calidad con voces realistas para tus contenidos",
    icon: <Headphones className="h-8 w-8 text-purple-700" />,
    status: "disconnected",
    category: "marketing",
    popularityScore: 86,
  },
  {
    id: "shopify",
    name: "Shopify",
    description: "Integra tu tienda online para sincronizar productos y pedidos",
    icon: <ShoppingBag className="h-8 w-8 text-green-700" />,
    status: "pending",
    category: "data",
    popularityScore: 93,
  },
  {
    id: "whatsapp",
    name: "WhatsApp",
    description: "Conecta tu cuenta de WhatsApp Business para atención al cliente",
    icon: <Phone className="h-8 w-8 text-green-500" />,
    status: "disconnected",
    category: "social",
    popularityScore: 91,
  },
  {
    id: "blog",
    name: "Blog",
    description: "Publica y gestiona contenido en tu blog WordPress o similar",
    icon: <Bookmark className="h-8 w-8 text-blue-400" />,
    status: "disconnected",
    category: "marketing",
    popularityScore: 79,
  },
];
